name: application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  logging: ^1.3.0
  widgetbook: ^3.23.0
  logger_helper:
    git:
      url: https://gitea.intelligent-system.ru/train2026/Prof_26_Zahar.git
      ref: 21-05-26/1/logger
  ui_kit:
    git:
      url: https://gitea.intelligent-system.ru/train2026/Prof_26_Zahar.git
      ref: 21-05-26/1/ui-kit
  net_service:
    git:
      url: https://gitea.intelligent-system.ru/train2026/Prof_26_Zahar.git
      ref: 21-05-26/1/net-lib
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.2
  mocktail: ^1.0.5
  retrofit: ^4.9.2
  json_annotation: ^4.12.0
  retrofit_generator: ^10.2.6
  build_runner: ^2.15.0
  json_serializable: ^6.14.0
  image_picker: ^1.2.2
  file_picker: ^11.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
